config/routes.rb
Amdb::Application.routes.draw do

  resources :theaters


  root to: 'sessions#new'

  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  delete '/sessions' => 'sessions#destroy', as: 'session'

  resources :actors
  resources :directors
  resources :movies
  resources :roles
  resources :users
  resources :votes

end

app/models/actor.rb
class Actor < ActiveRecord::Base

  attr_accessible :name, :dob

  has_many :movies, :through => :roles

  has_many :roles, dependent: :destroy

  validates :name, presence: true

end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController

  def index
    @actors = Actor.all

    respond_to do |format|
      format.html { render 'index' }
      format.json { render json: @actors }
    end
  end

  def show
    @actor = Actor.find_by_id(params[:id])

    respond_to do |format|
      format.html { render 'show' }
      format.json { render json: @actor.roles }
    end
  end

  def new
    @actor = Actor.new
  end

  def create
    @actor = Actor.new(params[:actor])

    if @actor.save
      redirect_to actors_url
    else
      render 'new'
    end
  end

  def edit
    @actor = Actor.find_by_id(params[:id])
  end

  def update
    @actor = Actor.find_by_id(params[:id])

    if @actor.update_attributes(params[:actor])
      redirect_to @actor
    else
      render 'edit'
    end
  end

  def destroy
    @actor = Actor.find_by_id(params[:id])
    @actor.destroy
        redirect_to actors_url
      end
end

app/views/actors/_form.html.erb
<% if @actor.errors.any? %>
  <ul>
    <% @actor.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @actor do |f| %>
  <div>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :dob %><br />
    <%= f.text_field :dob %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing Actor #<%= @actor.id %></h1>

<%= render 'form' %>

app/views/actors/index.html.erb
<% a = Actor.last %>

<a href="http://localhost:3000/actors/<%= a.id %>">Show</a>
<%= link_to "Show", "http://localhost:3000/actors/#{a.id}" %>
<%= link_to "Show", actor_url(a.id) %>
<%= link_to "Show", actor_url(a) %>
<%= link_to "Show", a %>

<h1>Actors</h1>

<p><%= link_to 'Add a New Actor', new_actor_url %></p>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Dob</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @actors.each do |actor| %>
    <tr>
      <td><%= actor.name %></td>
      <td><%= actor.dob %></td>

      <td><%= link_to 'Show', actor %></td>
      <td><%= link_to 'Edit', edit_actor_url(actor) %></td>
      <td><%= link_to 'Destroy', actor, method: 'delete', data: { confirm: "Do you really want to delete this actor?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/actors/new.html.erb
<h1>New Actor</h1>

<%= render 'form' %>

app/views/actors/show.html.erb
<h1>Actor #<%= @actor.id %></h1>

<p>
  <b>Name:</b>
  <%= @actor.name %>
</p>

<p>
  <b>Dob:</b>
  <%= @actor.dob %>
</p>

<p>
  <b>Filmography:</b>
  <ul>
    <% @actor.movies.each do |movie| %>
      <li><%= link_to movie.title, movie %></li>
    <% end %>
  </ul>
</p>