config/routes.rb
Amdb::Application.routes.draw do

  resources :theaters


  root to: 'sessions#new'

  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  delete '/sessions' => 'sessions#destroy', as: 'session'

  resources :actors
  resources :directors
  resources :movies
  resources :roles
  resources :users
  resources :votes

end

app/models/director.rb
class Director < ActiveRecord::Base

  has_many :movies

  validates :name, presence: true

end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController

  def index
    @directors = Director.all

    respond_to do |format|
      format.html { render 'index' }
      format.json { render json: @directors }
    end
  end

  def show
    @director = Director.find_by_id(params[:id])

    respond_to do |format|
      format.html { render 'show' }
      format.json { render json: @directors }
    end
  end

  def new
    @director = Director.new
  end

  def create
    @director = Director.new
    @director.name = params[:name]

    if @director.save
            redirect_to directors_url
          else
      render 'new'
    end
  end

  def edit
    @director = Director.find_by_id(params[:id])
  end

  def update
    @director = Director.find_by_id(params[:id])
    @director.name = params[:name]

    if @director.save
            redirect_to directors_url
          else
      render 'edit'
    end
  end

  def destroy
    @director = Director.find_by_id(params[:id])
    @director.destroy
        redirect_to directors_url
      end
end

app/views/directors/edit.html.erb
<h1>Editing Director #<%= @director.id %></h1>

<% if @director.errors.any? %>
  <ul>
    <% @director.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_tag(director_url(@director), method: 'put') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @director.name %>
  </div>


  <div>
    <%= submit_tag "Update Director" %>
  </div>

<% end %>

app/views/directors/index.html.erb
<h1>Directors</h1>

<p><%= link_to 'Add a New Director', new_director_url %></p>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @directors.each do |director| %>
    <tr>
      <td><%= director.name %></td>

      <td><%= link_to 'Show', director_url(director) %></td>
      <td><%= link_to 'Edit', edit_director_url(director) %></td>
      <td><%= link_to 'Destroy', director_url(director), method: 'delete', data: { confirm: "Do you really want to delete this director?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/directors/new.html.erb
<h1>New Director</h1>

<% if @director.errors.any? %>
  <ul>
    <% @director.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_tag(directors_url, method: 'post') do %>


  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>


  <div>
    <%= submit_tag "Create Director" %>
  </div>
<% end %>

app/views/directors/show.html.erb
<h1>Director #<%= @director.id %></h1>

<p>
  <b>Name:</b>
  <%= @director.name %>
</p>