config/routes.rb
Amdb::Application.routes.draw do

  resources :theaters


  root to: 'sessions#new'

  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  delete '/sessions' => 'sessions#destroy', as: 'session'

  resources :actors
  resources :directors
  resources :movies
  resources :roles
  resources :users
  resources :votes

end

app/models/theater.rb
class Theater < ActiveRecord::Base
  attr_accessible :address, :name
end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  # GET /theaters
  # GET /theaters.json
  def index
    @theaters = Theater.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @theaters }
    end
  end

  # GET /theaters/1
  # GET /theaters/1.json
  def show
    @theater = Theater.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @theater }
    end
  end

  # GET /theaters/new
  # GET /theaters/new.json
  def new
    @theater = Theater.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @theater }
    end
  end

  # GET /theaters/1/edit
  def edit
    @theater = Theater.find(params[:id])
  end

  # POST /theaters
  # POST /theaters.json
  def create
    @theater = Theater.new(params[:theater])

    respond_to do |format|
      if @theater.save
        format.html { redirect_to @theater, notice: 'Theater was successfully created.' }
        format.json { render json: @theater, status: :created, location: @theater }
      else
        format.html { render action: "new" }
        format.json { render json: @theater.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /theaters/1
  # PUT /theaters/1.json
  def update
    @theater = Theater.find(params[:id])

    respond_to do |format|
      if @theater.update_attributes(params[:theater])
        format.html { redirect_to @theater, notice: 'Theater was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @theater.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theaters/1
  # DELETE /theaters/1.json
  def destroy
    @theater = Theater.find(params[:id])
    @theater.destroy

    respond_to do |format|
      format.html { redirect_to theaters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/views/theaters/_form.html.erb
<%= form_for(@theater) do |f| %>
  <% if @theater.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@theater.errors.count, "error") %> prohibited this theater from being saved:</h2>

      <ul>
      <% @theater.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br />
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/theaters/edit.html.erb
<h1>Editing theater</h1>

<%= render 'form' %>

<%= link_to 'Show', @theater %> |
<%= link_to 'Back', theaters_path %>

app/views/theaters/index.html.erb
<h1>Listing theaters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @theaters.each do |theater| %>
  <tr>
    <td><%= theater.name %></td>
    <td><%= theater.address %></td>
    <td><%= theater.created_at %></td>
    <td><%= theater.updated_at %></td>
    <td><%= link_to 'Show', theater %></td>
    <td><%= link_to 'Edit', edit_theater_path(theater) %></td>
    <td><%= link_to 'Destroy', theater, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Theater', new_theater_path %>

app/views/theaters/new.html.erb
<h1>New theater</h1>

<%= render 'form' %>

<%= link_to 'Back', theaters_path %>

app/views/theaters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @theater.name %>
</p>

<p>
  <b>Address:</b>
  <%= @theater.address %>
</p>

<p>
  <b>Created at:</b>
  <%= @theater.created_at %>
</p>

<p>
  <b>Updated at:</b>
  <%= @theater.updated_at %>
</p>


<%= link_to 'Edit', edit_theater_path(@theater) %> |
<%= link_to 'Back', theaters_path %>