config/routes.rb
Amdb::Application.routes.draw do

  resources :theaters


  root to: 'sessions#new'

  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  delete '/sessions' => 'sessions#destroy', as: 'session'

  resources :actors
  resources :directors
  resources :movies
  resources :roles
  resources :users
  resources :votes

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Amdb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Amdb</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Home", root_url %></li>
            <li><%= link_to "Directors", directors_url %></li>
            <li><%= link_to "Movies", movies_url %></li>
            <li><%= link_to "Actors", actors_url %></li>
            <li><%= link_to "Votes", votes_url %></li>
            <li><%= link_to "Users", users_url %></li>
            <% if signed_in? %>
              <li><%= link_to current_user.username, current_user %></li>
              <li><%= link_to "Sign Out", sessions_url, method: 'delete' %></li>
            <% else %>
              <li><%= link_to "Sign In", new_session_url %></li>
              <li><%= link_to "Sign Up", new_user_url %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">

    <% if notice.present? %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= notice %>
    </div>
    <% end %>

    <%= yield %>

    <hr>

    <footer>
      <p>&copy; Company 2012</p>
    </footer>

  </div>

</body>
</html>